/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as PuntosDeAcopioRouteImport } from './routes/puntos-de-acopio'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as VoluntariadoRouteImport } from './routes/voluntariado'
import { Route as CampanasIndexRouteImport } from './routes/campanas.index'
import { Route as CampanasSlugRouteImport } from './routes/campanas.$slug'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelAdminRouteImport } from './routes/panel.admin'
import { Route as PanelGestionRouteImport } from './routes/panel.gestion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PuntosDeAcopioRoute = PuntosDeAcopioRouteImport.update({
  id: '/puntos-de-acopio',
  path: '/puntos-de-acopio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntariadoRoute = VoluntariadoRouteImport.update({
  id: '/voluntariado',
  path: '/voluntariado',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasIndexRoute = CampanasIndexRouteImport.update({
  id: '/campanas/',
  path: '/campanas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanasSlugRoute = CampanasSlugRouteImport.update({
  id: '/campanas/$slug',
  path: '/campanas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/categorias/$slug',
  path: '/categorias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/panel/',
  path: '/panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/panel/admin',
  path: '/panel/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelGestionRoute = PanelGestionRouteImport.update({
  id: '/panel/gestion',
  path: '/panel/gestion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/puntos-de-acopio': typeof PuntosDeAcopioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparencia': typeof TransparenciaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/campanas/$slug': typeof CampanasSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/gestion': typeof PanelGestionRoute
  '/campanas/': typeof CampanasIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/puntos-de-acopio': typeof PuntosDeAcopioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparencia': typeof TransparenciaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/campanas/$slug': typeof CampanasSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/gestion': typeof PanelGestionRoute
  '/campanas': typeof CampanasIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/panel': typeof PanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/puntos-de-acopio': typeof PuntosDeAcopioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/transparencia': typeof TransparenciaRoute
  '/voluntariado': typeof VoluntariadoRoute
  '/campanas/$slug': typeof CampanasSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/panel/admin': typeof PanelAdminRoute
  '/panel/gestion': typeof PanelGestionRoute
  '/campanas/': typeof CampanasIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/panel/': typeof PanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/contacto'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/puntos-de-acopio'
    | '/reset-password'
    | '/transparencia'
    | '/voluntariado'
    | '/campanas/$slug'
    | '/categorias/$slug'
    | '/panel/admin'
    | '/panel/gestion'
    | '/campanas/'
    | '/categorias/'
    | '/panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/contacto'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/puntos-de-acopio'
    | '/reset-password'
    | '/transparencia'
    | '/voluntariado'
    | '/campanas/$slug'
    | '/categorias/$slug'
    | '/panel/admin'
    | '/panel/gestion'
    | '/campanas'
    | '/categorias'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/como-funciona'
    | '/contacto'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/puntos-de-acopio'
    | '/reset-password'
    | '/transparencia'
    | '/voluntariado'
    | '/campanas/$slug'
    | '/categorias/$slug'
    | '/panel/admin'
    | '/panel/gestion'
    | '/campanas/'
    | '/categorias/'
    | '/panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  PuntosDeAcopioRoute: typeof PuntosDeAcopioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TransparenciaRoute: typeof TransparenciaRoute
  VoluntariadoRoute: typeof VoluntariadoRoute
  CampanasSlugRoute: typeof CampanasSlugRoute
  CategoriasSlugRoute: typeof CategoriasSlugRoute
  PanelAdminRoute: typeof PanelAdminRoute
  PanelGestionRoute: typeof PanelGestionRoute
  CampanasIndexRoute: typeof CampanasIndexRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  PanelIndexRoute: typeof PanelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puntos-de-acopio': {
      id: '/puntos-de-acopio'
      path: '/puntos-de-acopio'
      fullPath: '/puntos-de-acopio'
      preLoaderRoute: typeof PuntosDeAcopioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntariado': {
      id: '/voluntariado'
      path: '/voluntariado'
      fullPath: '/voluntariado'
      preLoaderRoute: typeof VoluntariadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas/': {
      id: '/campanas/'
      path: '/campanas'
      fullPath: '/campanas/'
      preLoaderRoute: typeof CampanasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanas/$slug': {
      id: '/campanas/$slug'
      path: '/campanas/$slug'
      fullPath: '/campanas/$slug'
      preLoaderRoute: typeof CampanasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/categorias/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/panel'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/admin': {
      id: '/panel/admin'
      path: '/panel/admin'
      fullPath: '/panel/admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/gestion': {
      id: '/panel/gestion'
      path: '/panel/gestion'
      fullPath: '/panel/gestion'
      preLoaderRoute: typeof PanelGestionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  PuntosDeAcopioRoute: PuntosDeAcopioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TransparenciaRoute: TransparenciaRoute,
  VoluntariadoRoute: VoluntariadoRoute,
  CampanasSlugRoute: CampanasSlugRoute,
  CategoriasSlugRoute: CategoriasSlugRoute,
  PanelAdminRoute: PanelAdminRoute,
  PanelGestionRoute: PanelGestionRoute,
  CampanasIndexRoute: CampanasIndexRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  PanelIndexRoute: PanelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
